apiVersion: v1
kind: Service
metadata:
  name: student-backend-service
spec:
  type: NodePort
  selector:
    app: student-backend
  ports:
    - port: 8080       # Port exposed to cluster
      targetPort: 5000 # Port container listens to
      nodePort: 30007
